-- liquibase formatted sql

-- changeset fabiosiqueira:1727713654838-1
CREATE TABLE cart
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    consumer_id BIGINT,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    status      VARCHAR(255),
    CONSTRAINT pk_cart PRIMARY KEY (id)
);

-- changeset fabiosiqueira:1727713654838-2
CREATE TABLE cart_item
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id   BIGINT,
    product_name VARCHAR(255),
    category     VARCHAR(255),
    quantity     INTEGER,
    price        DECIMAL,
    cart_id      BIGINT,
    CONSTRAINT pk_cart_item PRIMARY KEY (id)
);

-- changeset fabiosiqueira:1727713654838-3
CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    price       DECIMAL,
    category    VARCHAR(255),
    CONSTRAINT pk_product PRIMARY KEY (id)
);

-- changeset fabiosiqueira:1727713654838-4
CREATE TABLE product_entity_images
(
    product_entity_id BIGINT NOT NULL,
    images            VARCHAR(255)
);

-- changeset fabiosiqueira:1727713654838-5
ALTER TABLE cart_item
    ADD CONSTRAINT FK_CART_ITEM_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);

-- changeset fabiosiqueira:1727713654838-6
ALTER TABLE product_entity_images
    ADD CONSTRAINT fk_productentity_images_on_product_entity FOREIGN KEY (product_entity_id) REFERENCES product (id);

