spring:
  application:
    name: fast-food-order
  main:
    lazy-initialization: true
  jmx:
    enabled: false
  mvc:
    problem-details:
      enabled: true
    jackson:
      default-property-inclusion: non_null
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      jakarta:
        persistence:
          validation:
            mode: none
  data:
    rest:
      default-media-type: application/json

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

jwt:
  secret-key: ${JWT_SECRET_KEY}Ï
