-- liquibase formatted sql

-- changeset fabiosiqueira:1747353326000-1
CREATE TABLE payment
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type           VARCHAR(255)                            NOT NULL,
    status         VARCHAR(255)                            NOT NULL,
    amount         DECIMAL                                 NOT NULL,
    transaction_id VARCHAR(255),
    qr_code        VARCHAR(255)                            NOT NULL,
    approved_at                         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_payment PRIMARY KEY (id)
);

-- changeset fabiosiqueira:1747353326000-2
ALTER TABLE orders
    ADD CONSTRAINT uc_orders_payment UNIQUE (payment_id);

-- changeset fabiosiqueira:1747353326000-3
ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_PAYMENT FOREIGN KEY (payment_id) REFERENCES payment (id);


