-- liquibase formatted sql

-- changeset fabiosiqueira:1727836924722-1
CREATE TABLE consumer
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    email VARCHAR(255),
    cpf   VARCHAR(255),
    CONSTRAINT pk_consumer PRIMARY KEY (id)
);

-- changeset fabiosiqueira:1727836924722-2
CREATE UNIQUE INDEX uk_consumer_cpf ON consumer (cpf);

