-- liquibase formatted sql

-- changeset fabiosiqueira:1727982891478-1
CREATE TABLE order_item
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id BIGINT                                  NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    price      DECIMAL                                 NOT NULL,
    subtotal   DECIMAL                                 NOT NULL,
    order_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_order_item PRIMARY KEY (id)
);

-- changeset fabiosiqueira:1727982891478-2
CREATE TABLE orders
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    consumer_id BIGINT,
    cart_id     BIGINT                                  NOT NULL,
    payment_id  BIGINT                                  NOT NULL,
    status      VARCHAR(255)                            NOT NULL,
    total       DECIMAL                                 NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

-- changeset fabiosiqueira:1727982891478-3
CREATE TABLE payment
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type           VARCHAR(255)                            NOT NULL,
    status         VARCHAR(255)                            NOT NULL,
    amount         DECIMAL                                 NOT NULL,
    transaction_id VARCHAR(255),
    qr_code        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_payment PRIMARY KEY (id)
);

-- changeset fabiosiqueira:1727982891478-4
ALTER TABLE orders
    ADD CONSTRAINT uc_orders_payment UNIQUE (payment_id);

-- changeset fabiosiqueira:1727982891478-5
CREATE INDEX idx_orders_consumer_id ON orders (consumer_id);

-- changeset fabiosiqueira:1727982891478-6
CREATE INDEX idx_orders_status ON orders (status);

-- changeset fabiosiqueira:1727982891478-7
CREATE UNIQUE INDEX uk_orders_cart_id ON orders (cart_id);

-- changeset fabiosiqueira:1727982891478-8
ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_PAYMENT FOREIGN KEY (payment_id) REFERENCES payment (id);

-- changeset fabiosiqueira:1727982891478-9
ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDER_ITEM_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

