-- liquibase formatted sql

-- changeset fabiosiqueira:1747353322000-1
CREATE TABLE order_item
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id BIGINT                                  NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    price      DECIMAL                                 NOT NULL,
    subtotal   DECIMAL                                 NOT NULL,
    order_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_order_item PRIMARY KEY (id)
);

-- changeset fabiosiqueira:1747353322000-2
CREATE TABLE orders
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    consumer_id VARCHAR(15)                             NOT NULL,
    cart_id     BIGINT                                  NOT NULL,
    payment_id  BIGINT                                  NOT NULL,
    status      VARCHAR(255)                            NOT NULL,
    total       DECIMAL                                 NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

-- changeset fabiosiqueira:1747353322000-3
CREATE INDEX idx_orders_status ON orders (status);

-- changeset fabiosiqueira:1747353322000-4
ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDER_ITEM_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

