-- liquibase formatted sql

-- changeset victorambiel:1736705220000-1
CREATE TABLE webhook_payment
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    payment_id      BIGINT          NOT NULL,
    action          VARCHAR(255)    NOT NULL,
    status          VARCHAR(255)    NOT NULL,
    date_created    TIMESTAMP       NOT NULL,
    CONSTRAINT pk_webhook_payment PRIMARY KEY (id)
);
